# Generated by Django 4.2.2 on 2023-06-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['-addedAt'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=100)),
                ('channelTitle', models.CharField(max_length=100)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'ordering': ['-addedAt'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ['-addedAt'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('publishedAt', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('viewCount', models.IntegerField(blank=True, null=True)),
                ('likeCount', models.IntegerField(blank=True, null=True)),
                ('commentCount', models.IntegerField(blank=True, null=True)),
                ('thumbnailUrl', models.URLField(blank=True, null=True)),
                ('videoUrl', models.URLField()),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='youtube_history.category')),
                ('playlist', models.ManyToManyField(to='youtube_history.playlist')),
                ('tag', models.ManyToManyField(to='youtube_history.tag')),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ['-publishedAt'],
            },
        ),
    ]
