# Generated by Django 4.2.2 on 2023-06-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='youtube_history.playlist'),
            preserve_default=False,
        ),
    ]
