# Generated by Django 4.2.2 on 2023-06-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0002_remove_video_playlist_video_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='youtube_history.playlist'),
        ),
    ]
