# Generated by Django 4.2.2 on 2023-06-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0004_alter_category_options_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
