# Generated by Django 4.2.2 on 2023-06-11 17:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0005_category_modified_on_playlist_modified_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['created_on'], 'verbose_name': 'Playlist'},
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
