# Generated by Django 4.2.2 on 2023-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0007_alter_video_created_on_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.CharField(default='#e60007', max_length=7),
        ),
        migrations.AddField(
            model_name='playlist',
            name='rank',
            field=models.SmallIntegerField(default=99),
        ),
    ]
