# Generated by Django 4.2.2 on 2023-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0009_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorting',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='ascending',
            field=models.BooleanField(default=True),
        ),
    ]
