# Generated by Django 4.2.2 on 2023-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0011_alter_playlist_options_alter_sorting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorting',
            name='default',
        ),
        migrations.AlterField(
            model_name='sorting',
            name='ascending',
            field=models.BooleanField(default=False),
        ),
    ]
