# Generated by Django 4.2.2 on 2023-06-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0013_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='top_comment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
