# Generated by Django 4.2.2 on 2023-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0015_rename_top_comment_video_top_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='top_comment_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
