# Generated by Django 4.2.2 on 2023-06-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0017_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['published_at'], 'verbose_name': 'Video'},
        ),
    ]
