# Generated by Django 4.2.2 on 2023-06-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0018_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['playlist__rank', '-published_at__year', 'published_at__hour', 'published_at__minute', 'title'], 'verbose_name': 'Video'},
        ),
    ]
