# Generated by Django 4.2.2 on 2023-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0019_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_api_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
