# Generated by Django 4.2.2 on 2023-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0021_playlist_page_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='total_videos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
