# Generated by Django 4.2.2 on 2023-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0022_playlist_total_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='request_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
