# Generated by Django 4.2.2 on 2023-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0023_playlist_request_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
