# Generated by Django 4.2.2 on 2023-07-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_history', '0024_alter_playlist_request_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='youtube_history.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='youtube_history.playlist'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='youtube_history.tag'),
        ),
    ]
